//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDelivery_Backend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cust_addr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_cust_addr()
        {
            this.tbl_cart_info = new HashSet<tbl_cart_info>();
        }
    
        public decimal cust_address_id { get; set; }
        public Nullable<decimal> cust_id { get; set; }
        public Nullable<decimal> cust_pin { get; set; }
        public string cust_address { get; set; }
        public string longitude { get; set; }
        public string latitude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_cart_info> tbl_cart_info { get; set; }
        public virtual tbl_cust_info tbl_cust_info { get; set; }
    }
}
