//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDelivery_Backend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_order_breakup
    {
        public decimal slno { get; set; }
        public Nullable<decimal> order_id { get; set; }
        public Nullable<decimal> food_id { get; set; }
        public string food_name { get; set; }
        public Nullable<decimal> supplier_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> price_per_item { get; set; }
    
        public virtual tbl_food_info tbl_food_info { get; set; }
        public virtual tbl_order_info tbl_order_info { get; set; }
        public virtual tbl_supplier_info tbl_supplier_info { get; set; }
    }
}
