//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDelivery_Backend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_supplier_menu
    {
        public string item_name { get; set; }
        public Nullable<decimal> item_rate { get; set; }
        public string item_type { get; set; }
        public decimal supplier_menu_id { get; set; }
        public Nullable<decimal> supplier_id { get; set; }
        public Nullable<decimal> food_id { get; set; }
        public Nullable<decimal> available_qty { get; set; }
        public string serv_cl_time { get; set; }
        public string serv_op_time { get; set; }
    
        public virtual tbl_food_info tbl_food_info { get; set; }
        public virtual tbl_supplier_info tbl_supplier_info { get; set; }
    }
}
