//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDelivery_Backend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_issue_info
    {
        public decimal dispute_no { get; set; }
        public Nullable<System.DateTime> raised_on { get; set; }
        public string issue_desc { get; set; }
        public string ticket_stat { get; set; }
        public string resolution { get; set; }
        public Nullable<System.DateTime> resolved_on { get; set; }
        public Nullable<decimal> trans_id { get; set; }
        public Nullable<decimal> order_id { get; set; }
    
        public virtual tbl_order_info tbl_order_info { get; set; }
        public virtual tbl_transaction_info tbl_transaction_info { get; set; }
    }
}
