//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDelivery_Backend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_delivery_info
    {
        public decimal sl_no { get; set; }
        public Nullable<decimal> transaction_id { get; set; }
        public Nullable<decimal> agent_id { get; set; }
        public string delivery_initiate_datetime { get; set; }
        public string delivered_datetime { get; set; }
        public string delivery_status { get; set; }
        public Nullable<decimal> comm_amt { get; set; }
    
        public virtual tbl_agent_info tbl_agent_info { get; set; }
    }
}
