//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDelivery_Backend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_food_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_food_info()
        {
            this.tbl_cart_info = new HashSet<tbl_cart_info>();
            this.tbl_order_breakup = new HashSet<tbl_order_breakup>();
            this.tbl_supplier_menu = new HashSet<tbl_supplier_menu>();
        }
    
        public decimal food_id { get; set; }
        public string food_type_cd { get; set; }
        public string food_name { get; set; }
        public string food_description { get; set; }
        public Nullable<decimal> food_qty { get; set; }
        public string food_img { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_cart_info> tbl_cart_info { get; set; }
        public virtual tbl_food_type tbl_food_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_order_breakup> tbl_order_breakup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_supplier_menu> tbl_supplier_menu { get; set; }
    }
}
