//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDelivery_Backend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_agent_wallet
    {
        public decimal agent_wallet_id { get; set; }
        public decimal agent_id { get; set; }
        public Nullable<decimal> wallet_balance { get; set; }
        public string last_updated_date { get; set; }
    
        public virtual tbl_agent_info tbl_agent_info { get; set; }
    }
}
