//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDelivery_Backend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_admin_info
    {
        public decimal emp_id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string status { get; set; }
        public string reg_date { get; set; }
        public Nullable<decimal> phone { get; set; }
        public string photo_id_no { get; set; }
        public string password { get; set; }
    }
}
