//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDelivery_Backend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cust_wallet
    {
        public decimal cust_wallet_id { get; set; }
        public Nullable<decimal> cust_id { get; set; }
        public Nullable<decimal> wallet_balance { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
    
        public virtual tbl_cust_info tbl_cust_info { get; set; }
    }
}
