//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDelivery_Backend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cust_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_cust_info()
        {
            this.tbl_cart_info = new HashSet<tbl_cart_info>();
            this.tbl_cust_addr = new HashSet<tbl_cust_addr>();
            this.tbl_cust_payment_mode = new HashSet<tbl_cust_payment_mode>();
            this.tbl_cust_wallet = new HashSet<tbl_cust_wallet>();
            this.tbl_order_info = new HashSet<tbl_order_info>();
            this.tbl_transaction_info = new HashSet<tbl_transaction_info>();
        }
    
        public decimal cust_id { get; set; }
        public string cust_type_cd { get; set; }
        public string cust_name { get; set; }
        public string cust_email { get; set; }
        public Nullable<decimal> cust_phno { get; set; }
        public Nullable<decimal> cust_pin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_cart_info> tbl_cart_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_cust_addr> tbl_cust_addr { get; set; }
        public virtual tbl_cust_type tbl_cust_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_cust_payment_mode> tbl_cust_payment_mode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_cust_wallet> tbl_cust_wallet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_order_info> tbl_order_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_transaction_info> tbl_transaction_info { get; set; }
    }
}
