//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDelivery_Backend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_agent_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_agent_info()
        {
            this.tbl_delivery_info = new HashSet<tbl_delivery_info>();
            this.tbl_order_info = new HashSet<tbl_order_info>();
            this.tbl_transaction_info = new HashSet<tbl_transaction_info>();
        }
    
        public decimal agent_id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string status { get; set; }
        public string reg_date { get; set; }
        public Nullable<decimal> phone { get; set; }
        public string photo_id_no { get; set; }
        public string password { get; set; }
        public string agent_type_cd { get; set; }
        public string agent_img { get; set; }
    
        public virtual tbl_agent_category tbl_agent_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_delivery_info> tbl_delivery_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_order_info> tbl_order_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_transaction_info> tbl_transaction_info { get; set; }
    }
}
