//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDelivery_Backend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_supplier_wallet
    {
        public decimal supplier_wallet_id { get; set; }
        public decimal supplier_id { get; set; }
        public Nullable<decimal> wallet_balance { get; set; }
        public string last_update_date { get; set; }
    
        public virtual tbl_supplier_info tbl_supplier_info { get; set; }
    }
}
