//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDelivery_Backend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VU_Supplier_FoodType_Info
    {
        public decimal supplier_id { get; set; }
        public string supplier_name { get; set; }
        public string supplier_address { get; set; }
        public Nullable<decimal> pincode { get; set; }
        public string reg_date { get; set; }
        public Nullable<decimal> supplier_gst_num { get; set; }
        public string supplier_type { get; set; }
        public string supplier_status { get; set; }
        public string longtitude { get; set; }
        public string latitude { get; set; }
        public string serv_pin_list { get; set; }
        public string supplier_email { get; set; }
        public string item_name { get; set; }
        public Nullable<decimal> item_rate { get; set; }
        public string item_type { get; set; }
        public decimal supplier_menu_id { get; set; }
        public Nullable<decimal> food_id { get; set; }
        public string food_type_code { get; set; }
        public Nullable<decimal> available_qty { get; set; }
        public string serv_cl_time { get; set; }
        public string serv_op_time { get; set; }
        public string food_type { get; set; }
        public string type_desc { get; set; }
        public string food_category { get; set; }
    }
}
